baseURL = 'https://jessmama.github.io/jsmablog/'

# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"

# language code
languageCode = 'en-us'
title = '程式設計師媽媽，與你分享兒童程式教育的學習資源 | 捷思媽'

# Change the default theme to be use when building the site with Hugo
theme = "FeelIt"

[params]
# site description
description = "程式設計師媽媽，與你分享兒童程式教育的學習資源 | 捷思媽"

# site keywords
keywords = ["scratch", "兒童程式","程式教育","scratch3.0","scratch遊戲","scratch範例","scratch教學範例","scratch遊戲設計","scratch教學","scratch程式","scratch程式設計","scratch課程","scratch兒童程式設計","程式語言兒童"]

# FeelIt theme version
version = "1.0.X"

# site default theme ("light", "dark", "auto")
defaultTheme = "light"

# public git repo url only then enableGitInfo is true
gitRepo = ""


# which hash function used for SRI, when empty, no SRI is used
# ("sha256", "sha384", "sha512", "md5")
fingerprint = ""

# date format
dateFormat = "2006-01-02"

# website images for Open Graph and Twitter Cards
images = ["/logo.png"]
  
# whether to enable CSS and JS source mapping
SourceMap = true

[menu]
  [[menu.main]]
    identifier = "posts"

    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""

    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"

    # title will be shown when you hover on this menu link
    title = ""
    weight = 1

  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2
    
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 3

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/khusika/FeelIt/issues/158)
    noClasses = false


[params.pwa]
    # whether to enable PWA support
    enable = true
    # service-worker version
    version = "1.0.1"

 # App icon config
  [params.app]
    # optional site title override for the app when added to an iOS home screen or Android launcher
    title = '程式設計師媽媽，與你分享兒童程式教育的學習資源 | 捷思媽'
    # whether to omit favicon resource links
    noFavicon = false
    # modern SVG favicon to use in place of older style .png and .ico files
    svgFavicon = ""
    # Android browser theme color
    themeColor = "#ffffff"
    # Safari mask icon color
    iconColor = "#5bbad5"
    # Windows v8-10 tile color
    tileColor = "#da532c"

# Search config
  [params.search]
    enable = true

    # type of search engine ("lunr", "algolia")
    type = "lunr"

    # max index length of the chunked content
    contentLength = 4000

    # placeholder of the search bar
    placeholder = ""

    # max number of results length
    maxResultLength = 10

    #  snippet length of the result
    snippetLength = 30

    # HTML tag name of the highlight part in results
    highlightTag = "em"

    # whether to use the absolute URL based on the baseURL in search index
    absoluteURL = false

    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""

  # Header config
  [params.header]

    # desktop header mode ("fixed", "normal", "auto")
    desktopMode = "fixed"

    # mobile header mode ("fixed", "normal", "auto")
    mobileMode = "auto"

    #  Header title config
    [params.header.title]
      # URL of the LOGO
      logo = ""

      # title name
      name = "捷思媽｜Jess媽"

      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""

      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""

      # whether to use typeit animation for title name
      typeit = false

      #  whether to show RSS icon
      rss = true

 
  # Footer config
  [params.footer]
    enable = true

    # Custom content (HTML format is supported)
    custom = ''

    # whether to show Hugo and theme info
    hugo = false

    #  whether to show copyright info
    copyright = true

    #  whether to show the author
    author = false

    # Site creation time
    since = 2021

    # ICP info only in China (HTML format is supported)
    icp = ""

    # license info (HTML format is supported)
    # license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
  
  # ection (all posts) page config
  [params.section]
    # special amount of posts in each section page
    paginate = 20

    # date format (month and day)
    dateFormat = "01-02"

    # amount of RSS pages
    rss = 10

  # List (category or tag) page config
  [params.list]

    # special amount of posts in each list page
    paginate = 20

    # date format (month and day)
    dateFormat = "01-02"

    # amount of RSS pages
    rss = 10

[params.about]
    # whether to enable profile on about page
    # depends on .Site.Params.home.profile.enable
    enable = true

    # whether to enable param layout
    param = true

    # title for param layout
    paramTitle = "Personal Information"

    # general description of your site
    # can be write with markdown style
    description = "[FeelIt](https://github.com/khusika/FeelIt) is a **clean**, **elegant** but **advanced** blog theme for [Hugo](https://gohugo.io/) developed by [Khusika](https://khusika.com). It is based on the original [LoveIt Theme](https://github.com/dillonzq/LoveIt), [LeaveIt Theme](https://github.com/liuzc/LeaveIt), and [KeepIt Theme](https://github.com/Fastbyte01/KeepIt)."
    
    # description of your status
    [[params.about.status]]
      faIcon = "fas fa-building"
      title = "Company"
      desc = "FeelIt"

    [[params.about.status]]
      faIcon = "fas fa-briefcase fa-fw"
      title = "Occupation"
      desc = "Freelancer"

    [[params.about.status]]
      title = "Location"
      faIcon = "fas fa-map-marker-alt"
      desc = "Earth"

    # description of your parameter
    [[params.about.parameter]]
      language = "UI/UX"
      level = "80"

    [[params.about.parameter]]
      language = "HTML"
      level = "70"

    [[params.about.parameter]]
      language = "Go"
      level = "60"

  # Home page config
  [params.home]
    # amount of RSS pages
    rss = 10

    # Home page profile
    [params.home.profile]
      enable = true

      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""

      avatarURL = "/images/avatar.webp"

      # title shown in home page (HTML format is supported)
      title = ""

      # subtitle shown in home page
      subtitle = "I'm Jess，是程式設計師，也是媽媽，與你分享兒童程式的學習資源"

      # whether to use typeit animation for subtitle
      typeit = true

      # whether to show social links
      social = true

      # disclaimer (HTML format is supported)
      disclaimer = ""

    # Home page posts
    [params.home.posts]
      enable = true

      # special amount of posts in each home posts page
      paginate = 6

      # display image-preview
      imagePreview = true

      # replaced with hiddenFromHomePage in params.page

      # default behavior when you don't set "hiddenFromHomePage" in front matter
      defaultHiddenFromHomePage = false

 # oEmbed config
  [params.oembed]
    # Privacy config (https://gohugo.io/about/hugo-and-gdpr/)
    privacy = false

    [params.oembed.facebook]
      # Facebook Aplication Identity and Client Token (<APPID>|<CLIENTTOKEN>)
      accessToken = ""

    [params.oembed.twitter]
      enableDNT = false

  # Social config about the author
  [params.social]
     # GitHub = "xxxx"
     # Linkedin = ""
     # Twitter = "xxxx"
     # Instagram = "xxxx"
     Facebook = "xxxx"
     # Telegram = "xxxx"
     # Medium = ""
     # Gitlab = ""
     # Youtubelegacy = ""
     # Youtubecustom = ""
     Youtubechannel = ""
     # Tumblr = ""
     # Quora = ""
     # Keybase = ""
     # Pinterest = ""
     # Reddit = ""
     # Codepen = ""
     # FreeCodeCamp = ""
     # Bitbucket = ""
     # Stackoverflow = ""
     # Weibo = ""
    Email = "xxxx@xxxx.com"
    xda = "" 
    RSS = true 

  # 文章页面配置
  [params.page]
    # 是否在主页隐藏一篇文章
    hiddenFromHomePage = false

    # 是否在搜索结果中隐藏一篇文章
    hiddenFromSearch = false

    # 是否使用 twemoji
    twemoji = false

    # 是否使用 lightgallery
    lightgallery = false

    # 是否使用 ruby 扩展语法
    ruby = true

    # 是否使用 fraction 扩展语法
    fraction = true

    # 是否使用 fontawesome 扩展语法
    fontawesome = true

    #  是否使用 fontawesome 作为CDN源
    cdnfontawesome = true

    # 是否在文章页面显示原始 Markdown 文档链接
    linkToMarkdown = false

    # 是否显示链接以改善文章
    improveArticle = ""

    # 是否在 RSS 中显示全文内容
    rssFullText = false

    #  目录配置
    [params.page.toc]
      # 是否使用目录
      enable = true

      # 是否保持使用文章前面的静态目录
      keepStatic = true

      # 是否使侧边目录自动折叠展开
      auto = true

    # 代码配置
    [params.page.code]
      # 是否显示代码块的复制按钮
      copy = true

      # 默认展开显示的代码行数
      maxShownLines = 10

    # {{< link "https://katex.org/" KaTeX >}} 数学公式
    [params.page.math]
      enable = true

      # 默认块定界符是 $$ ... $$ 和 \\[ ... \\]
      blockLeftDelimiter = ""
      blockRightDelimiter = ""

      # 默认行内定界符是 $ ... $ 和 \\( ... \\)
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""

      # KaTeX 插件 copy_tex
      copyTex = true

      # KaTeX 插件 mhchem
      mhchem = true

    # {{< link "https://docs.mapbox.com/mapbox-gl-js" "Mapbox GL JS" >}} 配置
    [params.page.mapbox]
      # Mapbox GL JS 的 access token
      accessToken = ""

      # 浅色主题的地图样式
      lightStyle = "mapbox://styles/mapbox/light-v9"

      # 深色主题的地图样式
      darkStyle = "mapbox://styles/mapbox/dark-v9"

      # 是否添加 {{< link "https://docs.mapbox.com/mapbox-gl-js/api#navigationcontrol" NavigationControl >}}
      navigation = true

      # 是否添加 {{< link "https://docs.mapbox.com/mapbox-gl-js/api#geolocatecontrol" GeolocateControl >}}
      geolocate = true

      # 是否添加 {{< link "https://docs.mapbox.com/mapbox-gl-js/api#scalecontrol" ScaleControl >}}
      scale = true

      # 是否添加 {{< link "https://docs.mapbox.com/mapbox-gl-js/api#fullscreencontrol" FullscreenControl >}}
      fullscreen = true

    #文章页面的分享信息设置
    [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Linkedin = false
      Whatsapp = false
      Pinterest = false
      Tumblr = false
      HackerNews = false
      Reddit = false
      VK = false
      Buffer = false
      Xing = false
      Line = true
      Instapaper = false
      Pocket = false
      Digg = false
      Stumbleupon = false
      Flipboard = false
      Weibo = true
      Renren = false
      Myspace = true
      Blogger = true
      Baidu = false
      Odnoklassniki = false
      Evernote = true
      Skype = false
      Trello = false
      Mix = false
    
    # 评论系统设置
    [params.page.comment]
      enable = false

      # Disqus 评论系统设置
      [params.page.comment.disqus]

        # FeelIt 新增 | 0.1.1
        enable = false

        # Disqus 的 shortname，用来在文章中启用 Disqus 评论系统
        shortname = ""

      # Vssue 评论系统设置 (https://github.com/meteorlxy/vssue)
      [params.page.comment.vssue]
        enable = false

        # Vssue 平台 API ("bitbucket", "gitea", "gitee", "github", "github-v4", "gitlab")
        platform = ""
        owner = ""
        repo = ""
        clientId = ""
        clientSecret = ""

      # Gitalk 评论系统设置
      [params.page.comment.gitalk]
        enable = false
        owner = ""
        repo = ""
        clientId = ""
        clientSecret = ""

      # Valine 评论系统设置
      [params.page.comment.valine]
        enable = false
        appId = ""
        appKey = ""
        placeholder = ""
        avatar = "mp"
        meta= ""
        pageSize = 10
        lang = ""
        visitor = true
        recordIP = true
        highlight = true
        enableQQ = false
        serverURLs = ""

        # emoji 数据文件名称, 默认是 "google.yml"
        # ("apple.yml", "google.yml", "facebook.yml", "twitter.yml")
        # 位于 "themes/FeelIt/assets/data/emoji/" 目录
        # 可以在你的项目下相同路径存放你自己的数据文件:
        # "assets/data/emoji/"
        emoji = ""

      # Facebook 评论系统设置
      [params.page.comment.facebook]
        enable = false
        width = "100%"
        numPosts = 10
        appId = ""
        languageCode = "zh_CN"


      # Telegram Comments 评论系统设置
      [params.page.comment.telegram]
        enable = false
        siteID = ""
        limit = 5
        height = ""
        color = ""
        colorful = true
        dislikes = false
        outlined = false
      
      # Commento 评论系统设置
      [params.page.comment.commento]
        enable = false

      # Utterances 评论系统设置
      [params.page.comment.utterances]
        enable = false
        # owner/repo
        repo = ""
        issueTerm = "pathname"
        label = ""
        lightTheme = "github-light"
        darkTheme = "github-dark"

    # 第三方库配置
    [params.page.library]
      [params.page.library.css]
        # someCSS = "some.css"
        # 位于 "assets/"
        # 或者
        # someCSS = "https://cdn.example.com/some.css"

      [params.page.library.js]
        # someJavascript = "some.js"
        # 位于 "assets/"
        # 或者
        # someJavascript = "https://cdn.example.com/some.js"

    # 页面 SEO 配置
    [params.page.seo]
      # 图片 URL
      images = []
      # 出版者信息
      [params.page.seo.publisher]
        name = ""
        logoUrl = ""

  # TypeIt 配置
  [params.typeit]
    # 每一步的打字速度 (单位是毫秒)
    speed = 100
    # 光标的闪烁速度 (单位是毫秒)
    cursorSpeed = 1000
    # 光标的字符 (支持 HTML 格式)
    cursorChar = "|"
    # 打字结束之后光标的持续时间 (单位是毫秒, "-1" 代表无限大)
    duration = -1

  # 网站验证代码，用于 Google/Bing/Yandex/Pinterest/Baidu
  [params.verification]
    google = ""
    bing = ""
    yandex = ""
    pinterest = ""
    baidu = ""

  # 网站 SEO 配置
  [params.seo]
    # 图片 URL
    image = ""
    # 缩略图 URL
    thumbnailUrl = ""

  # 网站分析配置
  [params.analytics]
    enable = false

    # Google Analytics 相关隐私 (被 privacy.googleAnalytics 替代)
    [params.analytics.google]
      id = ""

      # 是否匿名化用户 IP
      anonymizeIP = true

    # Fathom Analytics
    [params.analytics.fathom]
      id = ""

      # 自行托管追踪器时的主机路径
      server = ""

    # GoatCounter Analytics
    [params.analytics.goatcounter]
      # GoatCounter code
      code = ""

  # Cookie 许可配置
  [params.cookieconsent]
    enable = true

    # 用于 Cookie 许可横幅的文本字符串
    [params.cookieconsent.content]
      message = ""
      dismiss = ""
      link = ""

  # 第三方库文件的 CDN 设置
  [params.cdn]
    # CDN 数据文件名称, 默认不启用
    # ("jsdelivr.yml")
    # 位于 "themes/FeelIt/assets/data/cdn/" 目录
    # 可以在你的项目下相同路径存放你自己的数据文件:
    # "assets/data/cdn/"
    data = ""

  # 兼容性设置
  [params.compatibility]
    # 是否使用 Polyfill.io 来兼容旧式浏览器
    polyfill = false

    # 是否使用 object-fit-images 来兼容旧式浏览器
    objectFit = false

# Hugo 解析文档的配置
[markup]
  # 语法高亮设置
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false 是必要的设置
    # (https://github.com/khusika/FeelIt/issues/158)
    noClasses = false
  
  # Goldmark 是 Hugo 0.60 以来的默认 Markdown 解析库
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    
    [markup.goldmark.renderer]
      # 是否在文档中直接使用 HTML 标签
      unsafe = true
  
  # 目录设置
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# 作者配置
[author]
  name = "捷思媽"
  email = ""
