# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - main  # 當main分支有push操作時

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
       # 使用當前的 repo
       - name: checkout private repo
         uses: actions/checkout@v2
         with:
            ref: main
            token: ${{ secrets.HUGO_DEPLOY_TOKEN  }}
            submodules: true  # 找尋Hugo主題(true OR recursive)
            fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

       - name: Setup Hugo
         uses: peaceiris/actions-hugo@v2
         with:
           hugo-version: 'latest'
           extended: true
           
       - name: Setup Theme Dependency
         run: npm run reinstall --prefix themes/FeelIt
        
       # 我發現 Hugo 會產生一堆 min.[hash].* 檔案，所以這裡我先把舊檔案清除
       - name: cleanup files of public site
         working-directory: ./public
         shell: bash
         run: find . -type f -name '*.min.*' -exec rm -f {} \;
         
      # 開始用 Hugo 產生檔案囉
       - name: build content to public site
         working-directory: ./
         run: hugo --minify --gc      
     
       - name: Deploy
         uses: peaceiris/actions-gh-pages@v3
         with:
          github_token: ${{ secrets.HUGO_DEPLOY_TOKEN }}
          PUBLISH_BRANCH: gh-pages  # 推送到 gh-pages 分支
          PUBLISH_DIR: ./public     # hugo 生成的目錄
          commit_message: ${{ github.event.head_commit.message }}
