# This is a basic workflow to help you get started with Actions

name: Deploy Hugo Site to Github Pages

on:
  push:
    branches:
      - main  # 當main分支有push操作時
  
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
       - name: checkout private repo
         uses: actions/checkout@v2
         with:
            submodules: true  # 找尋Hugo主題(true OR recursive)
            fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
            
       - name: Setup Hugo
         uses: peaceiris/actions-hugo@v2
         with:
            hugo-version: '0.83.1'
            extended: true

      # - name: Clean public
      #   run: rm -rf public/*
         
      # - name: Setup public
      #   run: git worktree add -B gh-pages public origin/gh-pages
      
       - name: build content to public site
         #working-directory: ./
         run: hugo #--minify   
     
       - name: Deploy
         uses: peaceiris/actions-gh-pages@v3
         with:
          github_token: ${{ secrets.HUGO_DEPLOY_TOKEN }}
          PUBLISH_BRANCH: gh-pages  # 推送到 gh-pages 分支
          PUBLISH_DIR: ./public     # hugo 生成的目錄
          keep_files: false # remove existing files
          commit_message: ${{ github.event.head_commit.message }}
